# Generated by Django 6.0.2 on 2026-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weather', models.CharField(max_length=20)),
                ('Temperature', models.CharField(help_text='Temperature: Hot, Mild, Cool', max_length=10)),
                ('Humidity', models.CharField(max_length=10)),
                ('Wind', models.CharField(max_length=10)),
                ('Weekend', models.BooleanField(default=False, help_text='True if weekend (Yes), False if weekday (No)')),
                ('Ground_Condition', models.CharField(max_length=20)),
                ('Play_Football', models.BooleanField(default=True, help_text='True if football is played (Yes), False if not (No)')),
            ],
        ),
    ]
