# Generated by Django 6.0.2 on 2026-04-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLapp', '0002_footballmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballmatch',
            name='Play_Football',
            field=models.BooleanField(help_text='True if football is played (Yes), False if not (No)'),
        ),
    ]
