# Generated by Django 6.0.2 on 2026-04-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLapp', '0004_alter_footballmatch_play_football'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballmatch',
            name='Weekend',
            field=models.CharField(max_length=20),
        ),
    ]
