# Generated by Django 6.0.2 on 2026-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size_sqft', models.IntegerField()),
                ('Bedrooms', models.IntegerField()),
                ('Bathrooms', models.IntegerField()),
                ('Age_years', models.IntegerField()),
                ('Distance_to_city_km', models.FloatField()),
                ('Location_type', models.CharField(max_length=30)),
                ('Condition', models.CharField(max_length=20)),
                ('House_Price', models.FloatField()),
            ],
        ),
    ]
