# Generated by Django 6.0.2 on 2026-04-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLapp', '0003_alter_footballmatch_play_football'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballmatch',
            name='Play_Football',
            field=models.CharField(help_text='True if football is played (Yes), False if not (No)', max_length=20),
        ),
    ]
