# Generated by Django 6.0.2 on 2026-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLapp', '0005_alter_footballmatch_weekend'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballBoostin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weather', models.CharField(max_length=20)),
                ('Temperature', models.CharField(help_text='Temperature: Hot, Mild, Cool', max_length=10)),
                ('Humidity', models.CharField(max_length=10)),
                ('Wind', models.CharField(max_length=10)),
                ('Weekend', models.CharField(max_length=20)),
                ('Ground_Condition', models.CharField(max_length=20)),
                ('Play_Football', models.CharField(help_text='True if football is played (Yes), False if not (No)', max_length=20)),
                ('Time_of_Day', models.CharField(help_text='Time of Day: Morning, Afternoon, Evening', max_length=20)),
            ],
        ),
    ]
