# Generated by Django 6.0.2 on 2026-08-31 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MLapp', '0006_footballboostin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FootballBoostin',
            new_name='Footballclassification',
        ),
    ]
